# Generated by Django 4.2.21 on 2026-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_quiz_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='intro_title',
            field=models.CharField(blank=True, default='Kaun Banega Crorepati', max_length=200),
        ),
    ]
