# Generated by Django 4.2.21 on 2026-06-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_alter_quiz_intro_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
