# Generated by Django 4.2.21 on 2026-06-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_quizattempt_question_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotseatattempt',
            name='showing_question',
            field=models.BooleanField(default=False),
        ),
    ]
