# Generated by Django 4.2.21 on 2026-06-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_alter_hotseatattempt_showing_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('regular', 'Regular (Preliminary)'), ('fff_1', 'Fastest Finger First (Batch 1)'), ('fff_2', 'Fastest Finger First (Batch 2)'), ('fff_3', 'Fastest Finger First (Batch 3)'), ('hotseat_1', 'Hotseat (Batch 1)'), ('hotseat_2', 'Hotseat (Batch 2)'), ('hotseat_3', 'Hotseat (Batch 3)'), ('switch', 'Switch Question'), ('buzzer', 'Buzzer Round Question')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='current_stage',
            field=models.CharField(choices=[('regular', 'Regular Preliminary Quiz'), ('batch_selection', 'Selecting Top 30 and Batches'), ('buzzer_round', 'Buzzer Round'), ('fff_batch_1', 'Fastest Finger First - Batch 1'), ('hotseat_batch_1', 'Hotseat - Batch 1'), ('fff_batch_2', 'Fastest Finger First - Batch 2'), ('hotseat_batch_2', 'Hotseat - Batch 2'), ('fff_batch_3', 'Fastest Finger First - Batch 3'), ('hotseat_batch_3', 'Hotseat - Batch 3'), ('completed', 'Event Completed')], default='regular', max_length=40),
        ),
        migrations.CreateModel(
            name='BuzzerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_timer_limit', models.IntegerField(default=15)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('timer_paused_at', models.DateTimeField(blank=True, null=True)),
                ('is_timer_running', models.BooleanField(default=False)),
                ('buzzers_locked', models.BooleanField(default=True)),
                ('options_visible', models.BooleanField(default=False)),
                ('answer_visible', models.BooleanField(default=False)),
                ('buzzer_mappings', models.JSONField(blank=True, default=dict)),
                ('incorrect_buzzers', models.JSONField(blank=True, default=list)),
                ('active_buzzer_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.question')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buzzer_state', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='BuzzerPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buzzer_id', models.CharField(max_length=50)),
                ('pressed_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzer_presses', to='quizzes.quiz')),
            ],
        ),
        migrations.AddConstraint(
            model_name='buzzerpress',
            constraint=models.UniqueConstraint(fields=('quiz', 'question', 'buzzer_id'), name='unique_buzzer_press_per_question'),
        ),
    ]
