# Generated by Django 4.2.21 on 2026-06-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buzzerstate',
            name='buzzer_count',
            field=models.IntegerField(default=15),
        ),
    ]
