# Generated by Django 4.2.21 on 2026-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_add_buzzer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotseatattempt',
            name='lifeline_expert_used',
            field=models.BooleanField(default=False),
        ),
    ]
