# Generated by Django 6.0.3 on 2026-06-22 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_remove_is_registration_open_optional_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='experts/')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='quizzes.quiz')),
            ],
        ),
    ]
