# Generated by Django 4.2.21 on 2026-06-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_team_member1_email_team_member1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systempreferences',
            name='expert_timer_limit',
            field=models.IntegerField(default=30),
        ),
    ]
