# Generated by Django 4.2.21 on 2026-06-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0029_expert_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='has_buzzer_round',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='has_fff_round',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='has_hotseat_round',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='has_prelim_round',
            field=models.BooleanField(default=True),
        ),
    ]
