# Generated by Django 4.2.21 on 2026-06-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cleartext_password_user_is_super_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], db_index=True, default='student', max_length=20),
        ),
    ]
