# Generated by Django 6.0.3 on 2026-06-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cleartext_password',
        ),
    ]
